# This is a basic workflow to help you get started with Actions

name: update-dependencies

# Controls when the workflow will run
on:
  # Triggers the workflow at 20pm thursday (depends on timezone) (0 18 * * THU)
  schedule:
    - cron: '0 21 * * THU'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update_dependencies:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 3.1
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1.301
          
      - name: Setup .NET 5
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 5.0.102

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install rollup
        run: npm install --global rollup@3.1.0

      - name: Update to latest nfdi4plants web components
        run: npm run updatecomponents

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update @nfdi4plants/web-components ⬆️
